/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SysAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise911;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.OrganizationDirectory;
import Business.Role.Enterprise911.Enterprise911Admin;
import Business.Role.FirstResponder.FirstRespAdmin;
import Business.Role.HealthCare.HealthCareAdmin;
import Business.Role.Role;
import Business.Role.SystemAdminRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Utilities.Profile;
import UI.MainJFrame;
import Util.MapsUtil;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author akshatajadhav
 */
public class AdminListJPanel extends javax.swing.JPanel {

    JLayeredPane mainPane;
    JLayeredPane workPane;
    EcoSystem system;
    ArrayList<Network> networkList;
    EnterpriseDirectory enterpriseDirectory;
    OrganizationDirectory organizationDirectory;
    Pattern emailPattern;
    Pattern phonePattern;
    Pattern passwordPattern;
    String selectedEnterprise;

    /**
     * Creates new form HosptialHomeJPanel
     */
    public AdminListJPanel(JLayeredPane mainPane, JLayeredPane workPane, EcoSystem system, String selectedEnterprise) {
        initComponents();
        this.mainPane = mainPane;
        this.workPane = workPane;
        this.system = system;
        this.networkList = system.getNetworkList();
        this.selectedEnterprise = selectedEnterprise;
        this.enterpriseDirectory = system.getNetworkList().get(0).getEnterpriseDirectory();

        String emailRegex = "^(.+)@(\\S+)$";
        emailPattern = Pattern.compile(emailRegex);

        String phoneRegex = "^\\d{10}$";
        phonePattern = Pattern.compile(phoneRegex);

        String passwordRegex = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$";
        passwordPattern = Pattern.compile(passwordRegex);

        radbtnMale.setActionCommand("Male");
        radbtnFemale.setActionCommand("Female");
        radbtnNotToSay.setActionCommand("PreferNotToSay");
        buttonGroup1.add(radbtnMale);
        buttonGroup1.add(radbtnFemale);
        buttonGroup1.add(radbtnNotToSay);

        if (selectedEnterprise.equalsIgnoreCase("Enterprise911")) {
            enterpriseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/Dispatcher_40px.png")));
            enterprise.setText("911 Enterprise");
        } else if (selectedEnterprise.equalsIgnoreCase("FirstResponderEnterprise")) {
            enterpriseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/police_car_48px.png")));
            enterprise.setText("First Responder Enterprise");
        } else if (selectedEnterprise.equalsIgnoreCase("HealthCareEnterprise")) {
            enterpriseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/hospital_48px.png")));
            enterprise.setText("Health Care Enterprise");
        }

//        populateEnterpriseCmbbox();
        populateEnterpriseAdminTable(selectedEnterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        EnterpriseADminJPanel = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblWorkAddress = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtWorkAddress = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        radbtnMale = new javax.swing.JRadioButton();
        radbtnFemale = new javax.swing.JRadioButton();
        radbtnNotToSay = new javax.swing.JRadioButton();
        btnUpdateAdmin = new javax.swing.JButton();
        btnCreateAdmin = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        enterprise = new javax.swing.JLabel();
        btnViewUser = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterpriseAdmin = new javax.swing.JTable();
        enterpriseIcon = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(990, 590));
        setMinimumSize(new java.awt.Dimension(990, 590));
        setPreferredSize(new java.awt.Dimension(990, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        EnterpriseADminJPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFirstName.setText("First Name : ");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setText("Last Name : ");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email : ");

        lblPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhoneNumber.setText("Phone Number : ");

        lblDateOfBirth.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDateOfBirth.setText("Date of Birth : ");

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAddress.setText("Address : ");

        lblWorkAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblWorkAddress.setText("Work Address : ");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGender.setText("Gender : ");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        buttonGroup1.add(radbtnMale);
        radbtnMale.setText("Male");

        buttonGroup1.add(radbtnFemale);
        radbtnFemale.setText("Female");
        radbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnFemaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(radbtnNotToSay);
        radbtnNotToSay.setText("Prefer not to say");
        radbtnNotToSay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnNotToSayActionPerformed(evt);
            }
        });

        btnUpdateAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateAdmin.setText("Update");
        btnUpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAdminActionPerformed(evt);
            }
        });

        btnCreateAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAdmin.setText("Create");
        btnCreateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAdminActionPerformed(evt);
            }
        });

        btnDeleteUser.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName.setText("User Name : ");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setText("Password: ");

        btnClear.setBackground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnterpriseADminJPanelLayout = new javax.swing.GroupLayout(EnterpriseADminJPanel);
        EnterpriseADminJPanel.setLayout(EnterpriseADminJPanelLayout);
        EnterpriseADminJPanelLayout.setHorizontalGroup(
            EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName)
                    .addComponent(lblEmail)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblAddress)
                    .addComponent(lblUserName))
                .addGap(14, 14, 14)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                        .addComponent(btnCreateAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(btnUpdateAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtAddress)
                        .addComponent(txtDateOfBirth)
                        .addComponent(txtEmail)
                        .addComponent(txtFirstName)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                        .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                                .addComponent(lblWorkAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhoneNumber)
                                    .addComponent(lblLastName)
                                    .addComponent(lblGender)
                                    .addComponent(lblPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                                            .addComponent(radbtnMale)
                                            .addGap(18, 18, 18)
                                            .addComponent(radbtnFemale)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radbtnNotToSay))
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(125, 125, 125))))
        );
        EnterpriseADminJPanelLayout.setVerticalGroup(
            EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterpriseADminJPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radbtnNotToSay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWorkAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EnterpriseADminJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateAdmin)
                    .addComponent(btnUpdateAdmin)
                    .addComponent(btnDeleteUser)
                    .addComponent(btnClear))
                .addGap(0, 0, 0))
        );

        add(EnterpriseADminJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 270));

        enterprise.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        enterprise.setText("Enterprise: ");
        add(enterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 320, 40));

        btnViewUser.setBackground(new java.awt.Color(255, 255, 255));
        btnViewUser.setText("View User");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });
        add(btnViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 103, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enterprise Administrators", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        tblEnterpriseAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact No.", "Email", "Work Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterpriseAdmin);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 960, -1));
        add(enterpriseIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 80, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void radbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnFemaleActionPerformed

    private void radbtnNotToSayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnNotToSayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radbtnNotToSayActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnUpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAdminActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEnterpriseAdmin.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a record to view admin details");
        }

        UserAccount selectedUser = (UserAccount) tblEnterpriseAdmin.getValueAt(selectedRowIndex, 0);
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String selectedEnterpriseAdmin = cmbboxEnterprise.getSelectedItem() != null ? String.valueOf(cmbboxEnterprise.getSelectedItem()) : null;

        try {
            String userName = txtUserName.getText();
            String phoneNumber = txtPhoneNumber.getText();
            String email = txtEmail.getText();
            String home = txtAddress.getText();
            String work = txtWorkAddress.getText();

            Matcher emailMatcher = emailPattern.matcher(email);
            Matcher phoneRegexMatcher = phonePattern.matcher(phoneNumber);

            //add address and work address
            if (StringUtils.isBlank(email) || !emailMatcher.matches()) {
                //add regex validations
                JOptionPane.showMessageDialog(this, "Please enter a valid email");
                return;
            } else if (StringUtils.isBlank(phoneNumber) || !phoneRegexMatcher.matches()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number");
                return;
            } else if (StringUtils.isBlank(home)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number");
                return;
            } else if (StringUtils.isBlank(work)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number");
                return;
            }

            //add validation for address
            boolean isUpdated = false;

            for (Network network : system.getNetworkList()) {
                this.enterpriseDirectory = network.getEnterpriseDirectory();
                if (enterpriseDirectory != null) {
                    for (Enterprise enterprise : enterpriseDirectory.getEnterpriseList()) {
                        if (enterprise != null && StringUtils.equalsIgnoreCase(enterprise.getEnterpriseType().getValue(), selectedEnterprise)) {
                            UserAccountDirectory accountDirectory = enterprise.getUserAccountDirectory();
                            if (accountDirectory != null && CollectionUtils.isNotEmpty(accountDirectory.getUserAccountList())) {
                                for (UserAccount account : accountDirectory.getUserAccountList()) {
                                    if (account != null && account.equals(selectedUser)) {
                                        Profile profile = account.getProfileDetails();
                                        if (profile != null) {
                                            profile.setEmail(email);
                                            profile.setPhone(Long.valueOf(phoneNumber));
                                            profile.setHomeAddress(home);
                                            profile.setWorkAddress(work);
                                            account.setProfileDetails(profile);
                                            isUpdated = true;
                                            JOptionPane.showMessageDialog(this, "User details updated Successfull!!");
                                        }
                                        break;
                                    }
                                }
                                enterprise.setUserAccountDirectory(accountDirectory);
                            }
                            if (!isUpdated) {
                                JOptionPane.showMessageDialog(this, "User updation failed");
                                return;
                            }
                            break;
                        }
                    }
                }
            }
            populateEnterpriseAdminTable(selectedEnterprise);
            enableAllFields(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid date of birth in yyyy-MM-dd.");
            return;
        }

    }//GEN-LAST:event_btnUpdateAdminActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEnterpriseAdmin.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a record to view admin details");
            return;
        }

        UserAccount selectedUser = (UserAccount) tblEnterpriseAdmin.getValueAt(selectedRowIndex, 0);
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        String selectedEnterpriseAdmin = cmbboxEnterprise.getSelectedItem() != null ? String.valueOf(cmbboxEnterprise.getSelectedItem()) : null;

        try {
            for (Network network : system.getNetworkList()) {
                this.enterpriseDirectory = network.getEnterpriseDirectory();
                if (enterpriseDirectory != null) {
                    for (Enterprise enterprise : enterpriseDirectory.getEnterpriseList()) {
                        if (enterprise != null && StringUtils.equalsIgnoreCase(enterprise.getEnterpriseType().getValue(), selectedEnterprise)) {
                            UserAccountDirectory accountDirectory = enterprise.getUserAccountDirectory();
                            if (accountDirectory != null && CollectionUtils.isNotEmpty(accountDirectory.getUserAccountList())) {
                                if (accountDirectory.removeUserAccount(selectedUser)) {
                                    system.deleteUsername(selectedUser.getUsername());
                                    JOptionPane.showMessageDialog(this, "User details deleted Successfully!!");
                                } else {
                                    JOptionPane.showMessageDialog(this, "User details delete operation failed!!");
                                }
                            }
                            break;
                        }
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid date of birth in yyyy-MM-dd.");
        }
        populateEnterpriseAdminTable(selectedEnterprise);
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnCreateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAdminActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //String selectedEnterpriseAdmin = cmbboxEnterprise.getSelectedItem() != null ? String.valueOf(cmbboxEnterprise.getSelectedItem()) : null;
        simpleDateFormat.setLenient(false);
        try {
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String firstName = txtFirstName.getText();
            String lastName = txtLastName.getText();
            String phoneNumber = txtPhoneNumber.getText();
            String email = txtEmail.getText();
            String home = txtAddress.getText();
            String work = txtWorkAddress.getText();

            Matcher emailMatcher = emailPattern.matcher(email);
            Matcher phoneRegexMatcher = phonePattern.matcher(phoneNumber);
            Matcher passworMatcher = passwordPattern.matcher(password);

            if (!system.isUniqueUsername(userName)) {
                JOptionPane.showMessageDialog(this, "Please enter a unique user Name");
                return;
            }

            //add address and work address
            if (StringUtils.isBlank(userName)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid user Name");
                return;
            } else if (StringUtils.isBlank(password) || !passworMatcher.matches()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid password");
                return;
            } else if (StringUtils.isBlank(firstName) || StringUtils.isNumeric(firstName)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid first Name");
                return;
            } else if (StringUtils.isBlank(lastName) || StringUtils.isNumeric(lastName)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid last Name");
                return;
            } else if (StringUtils.isBlank(email) || !emailMatcher.matches()) {
                //add regex validations
                JOptionPane.showMessageDialog(this, "Please enter a valid email");
                return;
            } else if (StringUtils.isBlank(phoneNumber) || !phoneRegexMatcher.matches()) {
                JOptionPane.showMessageDialog(this, "Please enter a valid phone number");
                return;
            } else if (buttonGroup1.getSelection() == null || StringUtils.isBlank(buttonGroup1.getSelection().getActionCommand())) {
                JOptionPane.showMessageDialog(this, "Please select an option for gender");
                return;
            } else if (StringUtils.isBlank(home)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid home address");
                return;
            } else if (StringUtils.isBlank(work)) {
                JOptionPane.showMessageDialog(this, "Please enter a valid work address");
                return;
            }

            String gender = buttonGroup1.getSelection().getActionCommand();
            Date dob = simpleDateFormat.parse(String.valueOf(txtDateOfBirth.getText()));

            double[] homeCoords = MapsUtil.getGeoPointFromAddress(home);
            if (homeCoords[0] == 0 || homeCoords[1] == 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid home address");
                return;
            }

            double[] coords = MapsUtil.getGeoPointFromAddress(work);
            if (coords[0] == 0 || coords[1] == 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid work address");
                return;
            }

            UserAccount userAccount = null;
            for (Enterprise enterprise : enterpriseDirectory.getEnterpriseList()) {
                if (enterprise != null && StringUtils.equalsIgnoreCase(enterprise.getEnterpriseType().getValue(), selectedEnterprise)) {
                    UserAccountDirectory accountDirectory = enterprise.getUserAccountDirectory();
//                    if (accountDirectory != null && accountDirectory.checkIfUsernameIsUnique(userName)) {
                    Profile userProfile = new Profile(firstName, lastName, gender, email, Long.valueOf(phoneNumber), dob, home, work);
                    Role role = null;
                    switch (enterprise.getEnterpriseType().getValue()) {
                        case "Enterprise911":
                            role = new Enterprise911Admin();
                            break;
                        case "FirstResponderEnterprise":
                            role = new FirstRespAdmin();
                            break;
                        case "HealthcareEnterprise":
                            role = new HealthCareAdmin();
                            break;
                    }
                    if (role != null) {
                        userAccount = accountDirectory.createUserAccount(userName, password, role, userProfile);
                    }
                    if (userAccount == null) {
                        JOptionPane.showMessageDialog(this, "User creation failed");
                        return;
                    }
                    enterprise.setUserAccountDirectory(accountDirectory);
                    system.addUsername(userName);
//                }
//                else {
//                        JOptionPane.showMessageDialog(this, "Enter a unique user name");
//                        return;
//                    }
                    break;
                }
            }
            populateEnterpriseAdminTable(selectedEnterprise);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter a valid date of birth in yyyy-MM-dd.");
            Logger.getLogger(AdminListJPanel.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnCreateAdminActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        int selectedRowIndex = tblEnterpriseAdmin.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a record to view admin details");
            return;
        }

        UserAccount userAccount = (UserAccount) tblEnterpriseAdmin.getValueAt(selectedRowIndex, 0);
        if (userAccount != null) {
            Profile adminProfile = userAccount.getProfileDetails();
            txtUserName.setText(userAccount.getUsername());
            txtPassword.setText(userAccount.getPassword());
            txtFirstName.setText(adminProfile.getFirstName());
            txtLastName.setText(adminProfile.getLastName());
            txtPhoneNumber.setText(String.valueOf(adminProfile.getPhone()));
            txtEmail.setText(adminProfile.getEmail());
            txtDateOfBirth.setText(simpleDateFormat.format(adminProfile.getDob()));
            txtAddress.setText(adminProfile.getHomeAddress());
            txtWorkAddress.setText(adminProfile.getWorkAddress());

            switch (adminProfile.getGender()) {
                case "Male":
                    buttonGroup1.setSelected(radbtnMale.getModel(), true);
                    break;
                case "Female":
                    buttonGroup1.setSelected(radbtnFemale.getModel(), true);
                    break;
                case "Prefer not to say":
                    buttonGroup1.setSelected(radbtnNotToSay.getModel(), true);
                    break;
            }
        }
        btnUpdateAdmin.setEnabled(true);
        btnCreateAdmin.setEnabled(false);
        enableAllFields(false);
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearAllFields();
        enableAllFields(true);
        btnUpdateAdmin.setEnabled(false);
        btnCreateAdmin.setEnabled(true);
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EnterpriseADminJPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateAdmin;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnUpdateAdmin;
    private javax.swing.JButton btnViewUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel enterprise;
    private javax.swing.JLabel enterpriseIcon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JRadioButton radbtnFemale;
    private javax.swing.JRadioButton radbtnMale;
    private javax.swing.JRadioButton radbtnNotToSay;
    private javax.swing.JTable tblEnterpriseAdmin;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtWorkAddress;
    // End of variables declaration//GEN-END:variables

//    private void populateEnterpriseCmbbox() {
//        cmbboxEnterprise.removeAllItems();
//        Arrays.asList(Enterprise.EnterpriseType.values()).stream().
//                filter(enterprise -> !StringUtils.equalsIgnoreCase(enterprise.getValue(), Enterprise.EnterpriseType.VoluntaryEnterprise.getValue()))
//                .forEach(enterprise -> cmbboxEnterprise.addItem(enterprise.getValue()));
//        cmbboxEnterprise.setSelectedIndex(0);
//    }
    private void populateEnterpriseAdminTable(String selectedEnterpriseAdmin) {
        DefaultTableModel enterpriseAdminTableModel = (DefaultTableModel) tblEnterpriseAdmin.getModel();
        enterpriseAdminTableModel.setRowCount(0);

        if (enterpriseDirectory != null) {
            for (Enterprise enterprise : enterpriseDirectory.getEnterpriseList()) {
                if (StringUtils.equalsIgnoreCase(enterprise.getEnterpriseType().getValue(), selectedEnterpriseAdmin)) {
                    UserAccountDirectory userAccountDirectory = enterprise.getUserAccountDirectory();
                    if (userAccountDirectory != null) {
                        List<UserAccount> enterpriseAdminUsers = userAccountDirectory.getUserAccountList();
                        if (CollectionUtils.isNotEmpty(enterpriseAdminUsers)) {
                            for (UserAccount user : enterpriseAdminUsers) {
                                Profile profile = user.getProfileDetails();
                                Object row[] = new Object[4];
                                row[0] = user;
                                row[1] = profile.getPhone();
                                row[2] = profile.getEmail();
                                row[3] = profile.getWorkAddress();
                                enterpriseAdminTableModel.addRow(row);
                            }
                        }
                    }
                }
            }
        }
        system.setNetworkList(networkList);
        btnUpdateAdmin.setEnabled(false);
        btnCreateAdmin.setEnabled(true);
        clearAllFields();
        enableAllFields(true);
    }

    private void clearAllFields() {
        txtUserName.setText("");
        txtPassword.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        txtDateOfBirth.setText("");
        txtAddress.setText("");
        txtWorkAddress.setText("");
        buttonGroup1.clearSelection();
    }

    private void enableAllFields(boolean enable) {
        txtUserName.setEditable(enable);
        txtPassword.setEditable(enable);
        txtFirstName.setEditable(enable);
        txtLastName.setEditable(enable);
        txtDateOfBirth.setEditable(enable);
        radbtnMale.setEnabled(enable);
        radbtnFemale.setEnabled(enable);
        radbtnNotToSay.setEnabled(enable);
    }
}
