/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Dispatcher;

import Business.Caller.Caller;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organization.FirstResponder.EMTOrganization;
import Business.Organization.FirstResponder.FireOrganization;
import Business.Organization.FirstResponder.LawEnforcementOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Util.DropdownItem;
import Util.MapsUtil;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author akshatajadhav
 */
public class AEmergencyJPanel extends javax.swing.JPanel {

    private EcoSystem system;
    private UserAccount userAccount;

    JLayeredPane mainPane;
    JLayeredPane workPane;

    WorkRequest workRequest;

    /**
     * Creates new form AEmergencyJPanel
     */
    public AEmergencyJPanel(JLayeredPane mainPane, JLayeredPane workPane, EcoSystem system, UserAccount userAccount, Caller caller, String message, String emergencyLevel) {
        initComponents();
        this.mainPane = mainPane;
        this.workPane = workPane;
        this.system = system;
        this.userAccount = userAccount;

        workRequest = new WorkRequest(this.userAccount.getWorkQueue().retrieveLastWRID() + 1); // pass the actual WR_ID.
        workRequest.setCaller(caller);
        workRequest.setMessage(message);
        workRequest.setEmergencyLevel(emergencyLevel.charAt(0));

        loadDropdowns();
        JPanel map = MapsUtil.defaultMap();
        displayPanel(maps, map);
    }

    private void loadDropdowns() {
        for (Network network : system.getNetworkList()) {
            Enterprise frEnterprise = network.getEnterpriseDirectory()
                    .findEnterprise(EnterpriseType.FirstResponderEnterprise.getValue());
            for (Organization org : frEnterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof EMTOrganization) {
                    this.loadValues(org, jComboBox2);
                } else if (org instanceof LawEnforcementOrganization) {
                    this.loadValues(org, jComboBox1);
                } else if (org instanceof FireOrganization) {
                    this.loadValues(org, jComboBox3);
                }
            }
        }
    }

    private void loadValues(Organization org, JComboBox<String> drpdown) {
        for (UserAccount acc : org.getUserAccountDirectory().getUserAccountList()) {
//            System.out.println(paramedicAccount.getUsername());
            drpdown.addItem(new DropdownItem(acc.getUsername(), acc).toString());
        }
    }

    public void displayPanel(JLayeredPane lpane, JPanel panel) {
        lpane.removeAll();
        lpane.add(panel);
        lpane.repaint();
        lpane.revalidate();
        JFrame parentFrame = (JFrame) SwingUtilities.getRoot(mainPane);
        parentFrame.pack();
        parentFrame.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        maps = new javax.swing.JLayeredPane();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(990, 590));
        setMinimumSize(new java.awt.Dimension(790, 550));
        setPreferredSize(new java.awt.Dimension(990, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(990, 2));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(990, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Police:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 403, 100, 22));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 402, 202, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 447, 202, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Paramedics:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 448, 110, 22));

        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 492, 202, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Fire Fighters:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 493, 110, 22));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Dispatch");
<<<<<<< HEAD
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 537, 113, -1));
=======
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
>>>>>>> 28be812632684dee0bfba94c84a0b0de36a8b917

        maps.setLayout(new java.awt.CardLayout());
        add(maps, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 990, 353));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Reset");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 367, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        workRequest.setReceiver((UserAccount) jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        workRequest.setReceiver((UserAccount) jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        workRequest.setReceiver((UserAccount) jComboBox3.getSelectedItem());
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // set sender of the WR as the current dispatcher.
        workRequest.setSender(userAccount);
        // set status of the WR.
        workRequest.setStatus("LTEOpen");
        // push the WR in the work queue of all the receivers and senders?
        userAccount.getWorkQueue().getWorkRequestList().add(workRequest);
        workRequest.getReceivers().forEach(receiver -> {
            receiver.getWorkQueue().getWorkRequestList().add(workRequest);
        }); 
        // redirect to the dispatcher home screen.
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLayeredPane maps;
    // End of variables declaration//GEN-END:variables
}
